package com.romic.fun_jvm

object OpCode {
  private def b(i: Int): Byte = (i & 0xff).toByte

  val nop: Byte = b(0x00)
  val aconst_null: Byte = b(0x01)
  val iconst_m1: Byte = b(0x02)
  val iconst_0: Byte = b(0x03)
  val iconst_1: Byte = b(0x04)
  val iconst_2: Byte = b(0x05)
  val iconst_3: Byte = b(0x06)
  val iconst_4: Byte = b(0x07)
  val iconst_5: Byte = b(0x08)
  val lconst_0: Byte = b(0x09)
  val lconst_1: Byte = b(0x0a)
  val fconst_0: Byte = b(0x0b)
  val fconst_1: Byte = b(0x0c)
  val fconst_2: Byte = b(0x0d)
  val dconst_0: Byte = b(0x0e)
  val dconst_1: Byte = b(0x0f)

  val bipush: Byte = b(0x10)
  val sipush: Byte = b(0x11)
  val ldc: Byte = b(0x12)
  val ldc_w: Byte = b(0x13)
  val ldc2_w: Byte = b(0x14)

  val iload: Byte = b(0x15)
  val lload: Byte = b(0x16)
  val fload: Byte = b(0x17)
  val dload: Byte = b(0x18)
  val aload: Byte = b(0x19)
  val iload_0: Byte = b(0x1a)
  val iload_1: Byte = b(0x1b)
  val iload_2: Byte = b(0x1c)
  val iload_3: Byte = b(0x1d)
  val lload_0: Byte = b(0x1e)
  val lload_1: Byte = b(0x1f)
  val lload_2: Byte = b(0x20)
  val lload_3: Byte = b(0x21)
  val fload_0: Byte = b(0x22)
  val fload_1: Byte = b(0x23)
  val fload_2: Byte = b(0x24)
  val fload_3: Byte = b(0x25)
  val dload_0: Byte = b(0x26)
  val dload_1: Byte = b(0x27)
  val dload_2: Byte = b(0x28)
  val dload_3: Byte = b(0x29)
  val aload_0: Byte = b(0x2a)
  val aload_1: Byte = b(0x2b)
  val aload_2: Byte = b(0x2c)
  val aload_3: Byte = b(0x2d)

  val iaload: Byte = b(0x2e)
  val laload: Byte = b(0x2f)
  val faload: Byte = b(0x30)
  val daload: Byte = b(0x31)
  val aaload: Byte = b(0x32)
  val baload: Byte = b(0x33)
  val caload: Byte = b(0x34)
  val saload: Byte = b(0x35)

  val istore: Byte = b(0x36)
  val lstore: Byte = b(0x37)
  val fstore: Byte = b(0x38)
  val dstore: Byte = b(0x39)
  val astore: Byte = b(0x3a)
  val istore_0: Byte = b(0x3b)
  val istore_1: Byte = b(0x3c)
  val istore_2: Byte = b(0x3d)
  val istore_3: Byte = b(0x3e)
  val lstore_0: Byte = b(0x3f)
  val lstore_1: Byte = b(0x40)
  val lstore_2: Byte = b(0x41)
  val lstore_3: Byte = b(0x42)
  val fstore_0: Byte = b(0x43)
  val fstore_1: Byte = b(0x44)
  val fstore_2: Byte = b(0x45)
  val fstore_3: Byte = b(0x46)
  val dstore_0: Byte = b(0x47)
  val dstore_1: Byte = b(0x48)
  val dstore_2: Byte = b(0x49)
  val dstore_3: Byte = b(0x4a)
  val astore_0: Byte = b(0x4b)
  val astore_1: Byte = b(0x4c)
  val astore_2: Byte = b(0x4d)
  val astore_3: Byte = b(0x4e)

  val iastore: Byte = b(0x4f)
  val lastore: Byte = b(0x50)
  val fastore: Byte = b(0x51)
  val dastore: Byte = b(0x52)
  val aastore: Byte = b(0x53)
  val bastore: Byte = b(0x54)
  val castore: Byte = b(0x55)
  val sastore: Byte = b(0x56)

  val pop: Byte = b(0x57)
  val pop2: Byte = b(0x58)
  val dup: Byte = b(0x59)
  val dup_x1: Byte = b(0x5a)
  val dup_x2: Byte = b(0x5b)
  val dup2: Byte = b(0x5c)
  val dup2_x1: Byte = b(0x5d)
  val dup2_x2: Byte = b(0x5e)
  val swap: Byte = b(0x5f)

  val iadd: Byte = b(0x60)
  val ladd: Byte = b(0x61)
  val fadd: Byte = b(0x62)
  val dadd: Byte = b(0x63)
  val isub: Byte = b(0x64)
  val lsub: Byte = b(0x65)
  val fsub: Byte = b(0x66)
  val dsub: Byte = b(0x67)
  val imul: Byte = b(0x68)
  val lmul: Byte = b(0x69)
  val fmul: Byte = b(0x6a)
  val dmul: Byte = b(0x6b)
  val idiv: Byte = b(0x6c)
  val ldiv: Byte = b(0x6d)
  val fdiv: Byte = b(0x6e)
  val ddiv: Byte = b(0x6f)
  val irem: Byte = b(0x70)
  val lrem: Byte = b(0x71)
  val frem: Byte = b(0x72)
  val drem: Byte = b(0x73)
  val ineg: Byte = b(0x74)
  val lneg: Byte = b(0x75)
  val fneg: Byte = b(0x76)
  val dneg: Byte = b(0x77)
  val ishl: Byte = b(0x78)
  val lshl: Byte = b(0x79)
  val ishr: Byte = b(0x7a)
  val lshr: Byte = b(0x7b)
  val iushr: Byte = b(0x7c)
  val lushr: Byte = b(0x7d)
  val iand: Byte = b(0x7e)
  val land: Byte = b(0x7f)
  val ior: Byte = b(0x80)
  val lor: Byte = b(0x81)
  val ixor: Byte = b(0x82)
  val lxor: Byte = b(0x83)
  val iinc: Byte = b(0x84)

  val i2l: Byte = b(0x85)
  val i2f: Byte = b(0x86)
  val i2d: Byte = b(0x87)
  val l2i: Byte = b(0x88)
  val l2f: Byte = b(0x89)
  val l2d: Byte = b(0x8a)
  val f2i: Byte = b(0x8b)
  val f2l: Byte = b(0x8c)
  val f2d: Byte = b(0x8d)
  val d2i: Byte = b(0x8e)
  val d2l: Byte = b(0x8f)
  val d2f: Byte = b(0x90)
  val i2b: Byte = b(0x91)
  val i2c: Byte = b(0x92)
  val i2s: Byte = b(0x93)

  val lcmp: Byte = b(0x94)
  val fcmpl: Byte = b(0x95)
  val fcmpg: Byte = b(0x96)
  val dcmpl: Byte = b(0x97)
  val dcmpg: Byte = b(0x98)

  val ifeq: Byte = b(0x99)
  val ifne: Byte = b(0x9a)
  val iflt: Byte = b(0x9b)
  val ifge: Byte = b(0x9c)
  val ifgt: Byte = b(0x9d)
  val ifle: Byte = b(0x9e)
  val if_icmpeq: Byte = b(0x9f)
  val if_icmpne: Byte = b(0xa0)
  val if_icmplt: Byte = b(0xa1)
  val if_icmpge: Byte = b(0xa2)
  val if_icmpgt: Byte = b(0xa3)
  val if_icmple: Byte = b(0xa4)
  val if_acmpeq: Byte = b(0xa5)
  val if_acmpne: Byte = b(0xa6)

  val goto: Byte = b(0xa7)
  val jsr: Byte = b(0xa8)
  val ret: Byte = b(0xa9)
  val tableswitch: Byte = b(0xaa)
  val lookupswitch: Byte = b(0xab)

  val ireturn: Byte = b(0xac)
  val lreturn: Byte = b(0xad)
  val freturn: Byte = b(0xae)
  val dreturn: Byte = b(0xaf)
  val areturn: Byte = b(0xb0)
  val return_ : Byte = b(0xb1)

  val getstatic: Byte = b(0xb2)
  val putstatic: Byte = b(0xb3)
  val getfield: Byte = b(0xb4)
  val putfield: Byte = b(0xb5)

  val invokevirtual: Byte = b(0xb6)
  val invokespecial: Byte = b(0xb7)
  val invokestatic: Byte = b(0xb8)
  val invokeinterface: Byte = b(0xb9)
  val invokedynamic: Byte = b(0xba)

  val new_ : Byte = b(0xbb)
  val newarray: Byte = b(0xbc)
  val anewarray: Byte = b(0xbd)
  val arraylength: Byte = b(0xbe)
  val athrow: Byte = b(0xbf)
  val checkcast: Byte = b(0xc0)
  val instanceof: Byte = b(0xc1)
  val monitorenter: Byte = b(0xc2)
  val monitorexit: Byte = b(0xc3)

  val wide: Byte = b(0xc4)
  val multianewarray: Byte = b(0xc5)
  val ifnull: Byte = b(0xc6)
  val ifnonnull: Byte = b(0xc7)
  val goto_w: Byte = b(0xc8)
  val jsr_w: Byte = b(0xc9)

  // Reserved opcodes, not generated by any legitimate compiler
  val breakpoint: Byte = b(0xca)
  val impdep1: Byte = b(0xfe)
  val impdep2: Byte = b(0xff)
}
